<?php get_header(); ?>
<section class="hero">
  <div class="hero__videos" aria-hidden="true">
    <?php foreach (['hero-1.mp4', 'hero-2.mp4', 'hero-3.mp4'] as $index => $video) : ?>
      <video class="hero__video<?php echo 0 === $index ? ' is-active' : ''; ?>" <?php echo 0 === $index ? 'autoplay' : ''; ?> muted loop playsinline preload="metadata"><source src="<?php echo esc_url(get_template_directory_uri() . '/assets/video/' . $video); ?>" type="video/mp4"></video>
    <?php endforeach; ?>
  </div>
  <div class="hero__content"><p class="eyebrow"><?php esc_html_e('Stories beyond the map', 'travel-riddle'); ?></p><h1><?php esc_html_e('Life is not meant to be lived in one place.', 'travel-riddle'); ?></h1><p class="hero__lede"><?php esc_html_e('Go beyond the postcard. Discover the feeling, people and quiet surprises that make a place unforgettable.', 'travel-riddle'); ?></p><div class="hero__meta"><a class="button" href="#latest"><?php esc_html_e('Begin exploring', 'travel-riddle'); ?></a><span class="hero__scroll"><?php esc_html_e('Scroll to wander', 'travel-riddle'); ?></span></div></div>
  <div class="hero__controls" aria-label="<?php esc_attr_e('Hero video slides', 'travel-riddle'); ?>"><?php for ($slide = 0; $slide < 3; $slide++) : ?><button type="button" class="slider-dot<?php echo 0 === $slide ? ' is-active' : ''; ?>" data-hero-slide="<?php echo esc_attr($slide); ?>" aria-label="<?php echo esc_attr(sprintf(__('Show video %d', 'travel-riddle'), $slide + 1)); ?>" aria-pressed="<?php echo 0 === $slide ? 'true' : 'false'; ?>"><span></span></button><?php endfor; ?></div>
</section>

<section class="section intro"><div class="wrap intro-grid"><div class="intro-image"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/intro-journey.png'); ?>" alt="<?php esc_attr_e('Traveler looking across a mountain valley at sunrise', 'travel-riddle'); ?>"><span><?php esc_html_e('Follow what makes you wonder', 'travel-riddle'); ?></span></div><div class="intro-copy"><p class="eyebrow"><?php esc_html_e('Why we travel', 'travel-riddle'); ?></p><h2><?php esc_html_e('Words may inspire a journey. Travel gives it a soul.', 'travel-riddle'); ?></h2><p class="intro-lead"><?php esc_html_e('There is something special about standing in a place you have only seen in photographs.', 'travel-riddle'); ?></p><p><?php esc_html_e('Feeling the air, hearing the sounds and meeting the people for yourself creates memories that pictures alone never can. We help you understand why a place is worth visiting—and whether it is right for you.', 'travel-riddle'); ?></p><a class="text-link" href="<?php echo esc_url(home_url('/about/')); ?>"><?php esc_html_e('Discover our philosophy', 'travel-riddle'); ?></a></div></div></section>

<section class="section stories" id="latest"><div class="wrap"><div class="section-head"><div><p class="eyebrow"><?php esc_html_e('Latest field notes', 'travel-riddle'); ?></p><h2><?php esc_html_e('Stories worth getting lost in', 'travel-riddle'); ?></h2></div><a class="text-link" href="<?php echo esc_url(get_post_type_archive_link('post') ?: home_url('/stories/')); ?>"><?php esc_html_e('View all stories', 'travel-riddle'); ?></a></div><div class="story-grid">
<?php $stories = new WP_Query(['post_type' => 'post', 'posts_per_page' => 5, 'ignore_sticky_posts' => true]); if ($stories->have_posts()) : while ($stories->have_posts()) : $stories->the_post(); ?>
  <a class="story-card" href="<?php the_permalink(); ?>"><div class="story-card__image"><?php if (has_post_thumbnail()) { the_post_thumbnail('travel-riddle-card'); } ?></div><div class="story-card__body"><p class="eyebrow"><?php echo esc_html(implode(' · ', wp_list_pluck(get_the_category(), 'name'))); ?> · <?php echo esc_html(travel_riddle_reading_time()); ?> min</p><h3><?php the_title(); ?></h3><p><?php echo esc_html(travel_riddle_excerpt(18)); ?></p></div></a>
<?php endwhile; wp_reset_postdata(); else :
$fallbacks = [
  ['Hidden corners, unforgettable light','The stories we bring home are often found beyond the itinerary.','story-mountains.png','Wild places'],
  ['The city after sunset','Local tables, old streets and an evening made for wandering.','story-city.png','Cities & culture'],
  ['The coast that time forgot','A quiet path to clear water, rugged cliffs and unhurried days.','story-coast.png','Coastal escapes'],
]; foreach ($fallbacks as $item) : ?>
  <a class="story-card" href="#"><div class="story-card__image"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/' . $item[2]); ?>" alt=""></div><div class="story-card__body"><p class="eyebrow"><?php echo esc_html($item[3]); ?></p><h3><?php echo esc_html($item[0]); ?></h3><p><?php echo esc_html($item[1]); ?></p><span class="story-card__read"><?php esc_html_e('Read the story', 'travel-riddle'); ?> →</span></div></a>
<?php endforeach; endif; ?>
</div></div></section>

<section class="section destinations"><div class="wrap"><div class="section-head"><div><p class="eyebrow"><?php esc_html_e('Choose your horizon', 'travel-riddle'); ?></p><h2><?php esc_html_e('Find a place that moves you', 'travel-riddle'); ?></h2></div><p><?php esc_html_e('From ancient streets to wild coastlines, follow your curiosity into landscapes and cultures worth knowing.', 'travel-riddle'); ?></p></div><div class="destination-grid"><?php $destinations = [['Mountains & wild places','story-mountains.png','Breathe deeper'],['Cities & culture','story-city.png','Stay curious'],['Coasts & islands','story-coast.png','Drift farther']]; foreach ($destinations as $destination) : ?><a class="destination-card" href="<?php echo esc_url(home_url('/destinations/')); ?>"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/' . $destination[1]); ?>" alt=""><div><span><?php echo esc_html($destination[2]); ?></span><h3><?php echo esc_html($destination[0]); ?></h3><b aria-hidden="true">↗</b></div></a><?php endforeach; ?></div></div></section>

<?php $travel_quotes = [
  ['Travel brings power and love back into your life.', 'Rumi'],
  ['Of all the books in the world, the best stories are found between the pages of a passport.', 'Anonymous'],
  ['Travel expands your brain.', 'Anonymous'],
  ['Travel brings out the best in you.', 'Anonymous'],
  ['The world is a book, and those who do not travel read only one page.', 'St. Augustine'],
  ['Investment in travel is an investment in yourself.', 'Matthew Karsten'],
  ['Fill your life with adventures, not things. Have stories to tell, not things to show.', 'Anonymous'],
  ['Anyone who needs more than one suitcase is a tourist, not a traveller.', 'Eva Levin'],
  ['Travel teaches tolerance.', 'Benjamin Disraeli'],
  ['Life is not meant to be lived in one place.', 'Anonymous'],
  ['One must travel to learn.', 'Mark Twain'],
  ['See the world. It is more fantastic than any dream.', 'Ray Bradbury'],
  ['Always say yes to new adventures.', 'Anonymous'],
  ['A traveler without observation is a bird without wings.', 'Moslih Eddin Saadi'],
  ['If you reject the food, ignore the customs, fear the religion, and avoid the people, you might better stay at home.', 'James Michener'],
]; ?>
<section class="quote-section"><aside class="founder-profile"><div class="founder-profile__image"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/founder.png'); ?>" alt="<?php esc_attr_e('MD. Hassan, founder of Travel Riddle', 'travel-riddle'); ?>"></div><p class="eyebrow"><?php esc_html_e('Founder and storyteller', 'travel-riddle'); ?></p><h3>MD. HASSAN</h3><p class="founder-profile__role"><?php esc_html_e('15+ years in the travel domain', 'travel-riddle'); ?></p><p><?php esc_html_e('Turning deep industry experience into thoughtful stories, practical insight and journeys with meaning.', 'travel-riddle'); ?></p></aside><div class="quote-copy"><p class="eyebrow"><?php esc_html_e('Thoughts for the road', 'travel-riddle'); ?></p><div class="quote-stage" aria-live="polite"><?php foreach ($travel_quotes as $index => $quote) : ?><figure class="quote-slide<?php echo 0 === $index ? ' is-active' : ''; ?>"><blockquote>“<?php echo esc_html($quote[0]); ?>”</blockquote><figcaption>— <?php echo esc_html($quote[1]); ?></figcaption></figure><?php endforeach; ?></div><div class="quote-controls"><button type="button" data-quote-prev aria-label="<?php esc_attr_e('Previous quote', 'travel-riddle'); ?>">←</button><span><b data-quote-current>01</b> / <?php echo esc_html(sprintf('%02d', count($travel_quotes))); ?></span><button type="button" data-quote-next aria-label="<?php esc_attr_e('Next quote', 'travel-riddle'); ?>">→</button></div></div></section>

<section class="section about-teaser"><div class="wrap"><div class="about-editorial"><div class="about-editorial__lead"><p class="eyebrow"><?php esc_html_e('Travel with purpose', 'travel-riddle'); ?></p><h2><?php esc_html_e('More than places. The stories that make them matter.', 'travel-riddle'); ?></h2><p><?php esc_html_e('Travel Riddle looks beyond lists and landmarks. We explore the people, traditions, flavours and quiet details that give every destination its character.', 'travel-riddle'); ?></p><a class="button" href="<?php echo esc_url(home_url('/about/')); ?>"><?php esc_html_e('Discover our story', 'travel-riddle'); ?></a></div><div class="about-principles"><article><span>01</span><h3><?php esc_html_e('Experience', 'travel-riddle'); ?></h3><p><?php esc_html_e('First-hand perspective shaped by more than fifteen years in travel.', 'travel-riddle'); ?></p></article><article><span>02</span><h3><?php esc_html_e('Curiosity', 'travel-riddle'); ?></h3><p><?php esc_html_e('Honest questions that reveal the soul behind a destination.', 'travel-riddle'); ?></p></article><article><span>03</span><h3><?php esc_html_e('Meaning', 'travel-riddle'); ?></h3><p><?php esc_html_e('Useful inspiration for journeys that stay with you.', 'travel-riddle'); ?></p></article></div></div></div></section>
<?php get_footer(); ?>
