<?php get_header();
$travel_quotes = [
['Travel Brings Power And Love Back into Your Life.','Rumi'],['Of All The Books In The World The Best Stories Are Found Between The Pages of a Passport.','Anonymous'],['Travel Expands Your Brain',''],['The Travel Brings out The Best in You.',''],['The World Is a Book, And Those Who Do Not Travel Read Only One Page.','St. Augustine'],['Investment In Travel Is An Investment In Yourself.','Matthew Karsten'],['Fill Your Life With Adventures, Not Things. Have Stories To Tell, Not Things To Show.','Anonymous'],['Anyone Who Needs More Than One Suitcase Is a Tourist, Not a Traveller.','Eva Levin'],['Travel Teaches Tolerance','Benjamin Disraeli'],['Life Is Not Meant To Be Lived In One Place.',''],['One Must Travel To Learn.','Mark Twain'],['See the World. It’s More Fantastic than Any Dream.','Ray Bradbury'],['Always Say Yes To New Adventures.',''],['A Traveler Without Observation Is a Bird Without Wings.','Moslih Eddin Saadi']]; ?>
<section class="hero hero--editorial">
  <div class="hero__videos" aria-hidden="true">
    <?php foreach (array_merge(range(1, 14), [16, 17]) as $index => $number) : ?>
      <video class="hero__video<?php echo 0 === $index ? ' is-active' : ''; ?>" <?php echo 0 === $index ? 'autoplay' : ''; ?> muted playsinline webkit-playsinline preload="<?php echo 0 === $index ? 'auto' : 'none'; ?>" poster="<?php echo esc_url(get_template_directory_uri() . '/assets/images/hero-poster-' . $number . '.webp'); ?>"><source src="<?php echo esc_url(get_template_directory_uri() . '/assets/video/hero-' . $number . '-web.mp4'); ?>" type="video/mp4"></video>
    <?php endforeach; ?>
  </div>
  <div class="hero-controls" aria-label="Banner video controls"><button type="button" data-video-pause aria-label="Pause banner videos">Pause</button><button type="button" data-video-next aria-label="Next banner video">Next →</button></div>
  <div class="hero-quote" aria-live="polite"><p class="hero-quote__label"><?php esc_html_e('A thought for the road','travel-riddle'); ?></p><div class="hero-quote__stage"><?php foreach ($travel_quotes as $index=>$quote) : ?><figure class="quote-slide<?php echo 0===$index?' is-active':''; ?>"><blockquote><?php echo esc_html($quote[0]); ?></blockquote><?php if ($quote[1]) : ?><figcaption>— <?php echo esc_html($quote[1]); ?></figcaption><?php endif; ?></figure><?php endforeach; ?></div><div class="hero-quote__nav"><button type="button" data-quote-prev aria-label="Previous quote">←</button><span><b data-quote-current>01</b> / <?php echo esc_html(sprintf('%02d',count($travel_quotes))); ?></span><button type="button" data-quote-next aria-label="Next quote">→</button></div></div>
</section>
<section class="section home-intro"><div class="wrap home-intro__grid"><div class="home-intro__image"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/intro-journey.png'); ?>" alt="Traveler looking across a mountain valley"></div><div class="home-intro__copy"><p class="eyebrow">Travel deeper</p><h1>Stories and guides for people who travel with curiosity.</h1><p class="intro-lead">Go beyond the postcard. Discover the people, places and quiet details that make every journey worth remembering.</p><a class="text-link" href="<?php echo esc_url(home_url('/about/')); ?>">Read our story</a></div></div></section>
<section class="section stories" id="latest"><div class="wrap"><div class="section-head"><div><p class="eyebrow">Latest from the journal</p><h2>Stories worth taking with you</h2></div><a class="text-link" href="<?php echo esc_url(home_url('/stories/')); ?>">See all stories</a></div><div class="story-grid story-grid--editorial">
<?php $stories=new WP_Query(['post_type'=>'post','posts_per_page'=>3,'ignore_sticky_posts'=>true]); if ($stories->have_posts()) : while ($stories->have_posts()) : $stories->the_post(); ?>
<article class="story-card story-card--editorial"><a class="story-card__image" href="<?php the_permalink(); ?>"><?php if (has_post_thumbnail()) the_post_thumbnail('travel-riddle-card'); ?></a><div class="story-card__body"><p class="eyebrow"><?php echo esc_html(implode(' · ',wp_list_pluck(get_the_category(),'name'))); ?> · <?php echo esc_html(travel_riddle_reading_time()); ?> min</p><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html(travel_riddle_excerpt(20)); ?></p><a class="text-link" href="<?php the_permalink(); ?>">Read story</a></div></article>
<?php endwhile; wp_reset_postdata(); else : $fallbacks=[['Hidden corners, unforgettable light','The stories we bring home are often found beyond the itinerary.','story-mountains.png','Wild places'],['The city after sunset','Local tables, old streets and an evening made for wandering.','story-city.png','Cities & culture'],['The coast that time forgot','A quiet path to clear water, rugged cliffs and unhurried days.','story-coast.png','Coastal escapes']]; foreach ($fallbacks as $item) : ?>
<article class="story-card story-card--editorial"><a class="story-card__image" href="<?php echo esc_url(home_url('/stories/')); ?>"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/'.$item[2]); ?>" alt=""></a><div class="story-card__body"><p class="eyebrow"><?php echo esc_html($item[3]); ?></p><h3><a href="<?php echo esc_url(home_url('/stories/')); ?>"><?php echo esc_html($item[0]); ?></a></h3><p><?php echo esc_html($item[1]); ?></p><a class="text-link" href="<?php echo esc_url(home_url('/stories/')); ?>">Read story</a></div></article>
<?php endforeach; endif; ?></div></div></section>
<section class="section destinations destinations--light"><div class="wrap"><div class="section-head"><div><p class="eyebrow">Explore by feeling</p><h2>Where do you want to go next?</h2></div><p>Find inspiration for mountain mornings, city nights and long days beside the sea.</p></div><div class="destination-grid"><?php $destinations=[['Mountains & wild places','story-mountains.png','Breathe deeper'],['Cities & culture','story-city.png','Stay curious'],['Coasts & islands','story-coast.png','Drift farther']]; foreach ($destinations as $destination) : ?><a class="destination-card" href="<?php echo esc_url(home_url('/destinations/')); ?>"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/'.$destination[1]); ?>" alt=""><div><span><?php echo esc_html($destination[2]); ?></span><h3><?php echo esc_html($destination[0]); ?></h3><b aria-hidden="true">↗</b></div></a><?php endforeach; ?></div></div></section>
<section class="section home-promise"><div class="wrap home-promise__inner"><div class="home-promise__copy"><p class="eyebrow">Travel Riddle</p><h2>Not just where to go.<br><em>Why it might stay with you.</em></h2><p>Thoughtful travel stories, useful ideas and destination inspiration for journeys with more meaning.</p><a class="button" href="<?php echo esc_url(home_url('/stories/')); ?>">Explore the journal</a></div><div class="travel-stamp" aria-hidden="true"><span>TR</span><b>Follow<br>curiosity</b><small>Est. 2026 · Stories beyond the map</small></div></div></section>
<?php get_footer(); ?>
